//! Wavetable sample bank — Waldorf Microwave user waves, baked into flash.
//!
//! The bytes are decoded from the Microwave SysEx dumps in
//! `patches/wavetables/*.mid` and stored at their **native** signed-8-bit depth
//! (the source is 8-bit; f32 storage would 4× the flash for precision that
//! doesn't exist — see BACKLOG.md "Waldorf wavetable osc"). Each wave is a full
//! 128-sample single cycle (the antisymmetric Waldorf half-wave already
//! mirrored at generation time), so the oscillator just indexes — no
//! reconstruction in the audio loop.
//!
//! Regenerate the blob (and the table metadata below) with:
//! ```text
//! python3 patches/wavetables/waldorf_wavetable.py rustbin \
//!     patches/wavetables/UW_XTUsersoundset3_and_VS-Waves.mid \
//!     daisy/crates/dsp/src/wavetables.bin
//! ```
//! The table ids/names/order MUST stay in lockstep with the browser bank
//! (`static/audio/wavetable/wavetables.json`) so a patch's `osc*_wavetable`
//! id selects the same waves on the Daisy as it previews in the editor.

/// Samples per single-cycle wave (power of two → mask wrap in the oscillator).
pub const WAVE_LEN: usize = 128;

/// All wave cycles concatenated, signed 8-bit, in `WT_TABLES` order. Flash
/// resident (`.rodata`); 215 waves × 128 = 27_520 bytes.
static WT_DATA: &[u8] = include_bytes!("wavetables.bin");

/// One named wavetable: a contiguous run of `count` waves starting at global
/// wave index `first` in `WT_DATA`.
pub struct WtTableDef {
    pub id: &'static str,
    pub name: &'static str,
    pub first: usize,
    pub count: usize,
}

/// The wavetables, in blob order. Generated by the `rustbin` command above.
pub static WT_TABLES: &[WtTableDef] = &[
    WtTableDef { id: "vswaves1", name: "VS-Waves 1", first: 0, count: 61 },
    WtTableDef { id: "xtuser", name: "XT User Waves", first: 61, count: 30 },
    WtTableDef { id: "ppgebass", name: "PPG E-Bass", first: 91, count: 63 },
    WtTableDef { id: "vswaves2", name: "VS-Waves 2", first: 154, count: 61 },
];

/// Total number of waves across all tables.
pub const WAVE_COUNT: usize = 215;

/// Look up a table by its string id (the patch's `osc*_wavetable`), falling
/// back to the first table for an unknown id so a stale patch can't panic.
pub fn table_by_id(id: &str) -> &'static WtTableDef {
    for t in WT_TABLES {
        if t.id == id {
            return t;
        }
    }
    &WT_TABLES[0]
}

/// One sample of a wave, normalized to roughly [-1.0, 1.0).
///
/// `wave` is a global wave index (0..`WAVE_COUNT`), `i` a sample index
/// (0..`WAVE_LEN`). The single `* (1/128)` is the only normalization the audio
/// path pays. `#[inline]` so it folds into the oscillator's hot loop.
#[inline(always)]
pub fn sample(wave: usize, i: usize) -> f32 {
    // Two's-complement reinterpret of the stored byte, then normalize.
    (WT_DATA[wave * WAVE_LEN + i] as i8) as f32 * (1.0 / 128.0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn blob_matches_metadata() {
        assert_eq!(WT_DATA.len(), WAVE_COUNT * WAVE_LEN);
        let total: usize = WT_TABLES.iter().map(|t| t.count).sum();
        assert_eq!(total, WAVE_COUNT);
        // Tables are contiguous and in order.
        let mut next = 0;
        for t in WT_TABLES {
            assert_eq!(t.first, next, "table {} not contiguous", t.id);
            next += t.count;
        }
    }

    #[test]
    fn samples_are_in_range() {
        for w in 0..WAVE_COUNT {
            for i in 0..WAVE_LEN {
                let s = sample(w, i);
                assert!((-1.0..=1.0).contains(&s), "sample {w}/{i} = {s} out of range");
            }
        }
    }

    #[test]
    fn unknown_id_falls_back_to_first() {
        assert_eq!(table_by_id("nope").id, WT_TABLES[0].id);
        assert_eq!(table_by_id("ppgebass").first, 91);
    }
}
